package uni.project.mylocalbooking.api;

public enum StatusCode {
    NO_CONTENT,
    NOT_FOUND,
    BAD_REQUEST,
    UNAUTHORIZED,
    UNPROCESSABLE_ENTITY,
    INTERNAL_SERVER_ERROR,
    JSONOBJECT_PARSE_ERROR,
    SESSION_PREFERENCES_NOT_FOUND,
    REQUEST_INTERRUPTED,
    CREATED;
}
